### PR TITLE
Refactor mendoza

### PR DESCRIPTION
**Pull request by Ashraf-Ali-aa**
Changes:
- Support filtering test cases
- Imported Slang to parse swift files
- Add some tests
- Add `swiftformat` file
- Move plugins to `.mendoza` folder
- Re-Add sandbox project to test Mendoza
- Support custom XCTestCase base class 

Note: Planning on migrate to Swift Argument Parser

### CODE REVIEW

**Comment by Ashraf-Ali-aa** [comment]
Hi @tcamin, any chance if you could look over this PR please, thanks

**Comment by tcamin** [comment]
Apologies for the late reply but it's an extremely busy period. Currently I'm unable to review the PR but I'll come back to as soon as I can. Sorry again for slow response on this.

**Comment by Ashraf-Ali-aa** [comment]
@tcamin Hey, I have rebased my changes with the latest updates

**Comment by tcamin** [comment]
While I really appreciate the contribution it is really difficult to review this and the subsequent reviews given the size and the surface of the changes. It would help to have smaller prs each with a one specific change, together with a motivation for the change which can be separately discussed.

Just as an example changing the default plugin folder is definitely something useful but it is a breaking change which cannot be merged in as is. It would be nice to have it customizable, maybe by prompting the user when initializing a plugin. Such a change deserves a pull request per se.

Wrt to formatting/linting I've recently added the swiftformat and swiftlint configuration files which follow our current internal styleguide and should not be modified.

Wrt to the include,exclude test list I'm really uncertain about the change, Mendoza is a niche tool which is used in contexts like continuous integratin which can be super specific (just as an example we don't use junit and rely on a separate tool to parse and present test results). I would prefer to keep the default functionality of the tool to a bare minimum and instead improve and work on plugins sandboxing. What about providing plugin example/templates that show how to do some common tasks (filtering plugins, etc.)? I believe that improving the plugin sandboxing (e.g. improve the way one debugs a plugin) can make the tool much more flexible that packing it with prebuilt feature which might not always respond to the user need. What do you think?

**Comment by Ashraf-Ali-aa** [comment]
Hey @tcamin, I do realise that I have made some breaking changes the reason behind it was I needed to get the tool working in a short amount of time. I'll create separate issues regarding the different changes hopefully this should give a better overview of the changes. 

regrading the swift format changes on a different PR I copied the previous rules to .swiftformat so that it uses the same file name as the tool https://github.com/nicklockwood/SwiftFormat/blob/master/.swiftformat

regarding the include,exclude tests this was one of my major requirements that I needed the tool to do, the idea behind it was that the UI test can be controlled by test management software or via a github pull request this would allow to run speficic tests based on the project requirements. I do agree the way I implemented could have been alot more configurable via the plugin architecture. The issue with the current setup is the plugin architecture does not support in pluginData via swift codable and also I don't have xcode autocomplete when writing swift code via swift shell scripts. Which lead me to my next point I want to separate the Mendoza tool into different swift targets i.e Mendoza (executable), MendozaCore (Core functionality), MendozaSharedLibrary and MendozaPlugin this would allow better testability and also to use swift package manager to extent mendoza

**Comment by Ashraf-Ali-aa** [comment]
Also, one thing to note I am trying to lay the groundworks so that Medoza can be fully tested from Unit level to E2E,  https://github.com/Subito-it/Mendoza/pull/5/files#diff-49abe6618ca5a692d09d1bd62e16d811

**Pull request closed without merging**
